/*
    TASK:
    AUTHOR: P
    SCHOOL: PCSHS
    LANG: C
*/
#include <stdio.h>
int main()
{
    int i,j,n,q;
    scanf("%d",&q);
    while(q--){
    scanf("%d",&n);
    for(i=0;i<1;i++)
    {
        for(j=0;j<n;j++)
                printf("*");
            printf("-");
            for(j=0;j<n;j++)
                printf("*");
            printf("-");
            for(j=0;j<n;j++)
                printf("*");
            printf("-");
            for(j=0;j<n;j++)
                if(j==0||j==n-1)
                {
                    printf("*");
                }
                else
                    printf("-");
            printf("\n");
    }
    for(i=0;i<(n-3)/2;i++)
    {
        printf("*");
        for(j=0;j<n-2;j++)
            printf("-");
        printf("*");
        printf("-");
        printf("*");
        for(j=0;j<n-2;j++)
            printf("-");
        printf("*");
        printf("-");
        printf("*");
        for(j=0;j<n;j++)
            printf("-");
        printf("*");
        for(j=0;j<i;j++)
            printf("-");
        printf("*");
        for(j=0;j<n-3-i;j++)
            printf("-");
        printf("*");
        printf("\n");
        }
    for(i=0;i<1;i++)
        {
            for(j=0;j<n;j++)
                    printf("*");
                printf("-");
                printf("*");
                for(j=0;j<n-2;j++)
                    printf("-");
                printf("*");
                printf("-");
                for(j=0;j<n;j++)
                    printf("*");
                printf("-");
                for(j=0;j<n;j++)
                    if(j==0||j==n-1||j==(n-1)/2)
                    {
                        printf("*");
                    }
                    else
                        printf("-");
                printf("\n");
        }
    for(i=0;i<(n-3)/2;i++)
    {
        printf("*");
        for(j=0;j<n;j++)
            printf("-");
        printf("*");
        for(j=0;j<n-2;j++)
            printf("-");
        printf("*");
        for(j=0;j<n;j++)
            printf("-");
        printf("*");
        printf("-");
        printf("*");
        for(j=0;j<(n-1)/2+i;j++)
            printf("-");
        printf("*");
        for(j=0;j<(n-3)/2-1-i;j++)
            printf("-");
        printf("*");
        printf("\n");
    }
    for(i=0;i<1;i++)
    {
            printf("*");
            for(j=0;j<n;j++)
                printf("-");
            for(j=0;j<n;j++)
                printf("*");
            printf("-");
            for(j=0;j<n;j++)
                printf("*");
            printf("-");
            for(j=0;j<n;j++)
                if(j==0||j==n-1)
                {
                    printf("*");
                }
                else
                    printf("-");
            printf("\n");
    }
    }
    return 0;
}
